### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by rmey** [data-henrik/Bluemix-onprem-data#1]
Hello Henrik, I got it working, thanks for the update.
Some remarks:
1. I was using Docker Secure Gateway Client. In that case the destination IP must be the Docker Host IP.
And MySQL daemon must listen on that IP (default 127.0.0.1 only, 0.0.0.0 for all interfaces).
1. The new Sec Gateway has the concept of worker id. The worker id need sometimes to specified, when interactively acl or configuration data of the Gateway  need to be viewed or chnaged. Each Secway client connected get its own worker id displayed as client ID with a number, with one client only usually 1.
2. The URI of new items posted in the app must include a protocol like http://www.google.de, when posting www.google.de the produced link on the page will be  appurl/www.google.de which is not valid.

**Comment by data-henrik** [comment]
Looking into it

**Comment by data-henrik** [comment]
I updated the section on Secure Gateway to account for the UI changes
